// Generated by Template Studio for WinUI 3 not Me

using System;
using System.Threading.Tasks;

using Lamina.Activation;
using Lamina.Contracts.Services;
using Lamina.Core.Contracts.Services;
using Lamina.Core.Services;
using Lamina.Models;
using Lamina.Services;
using Lamina.ViewModels;
using Lamina.Views;

using LaunchActivatedEventArgs = Microsoft.UI.Xaml.LaunchActivatedEventArgs;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media.Animation;

namespace Lamina
{
    public partial class App : Application
    {
        public IHost Host { get; }

        public static T GetService<T>() where T : class
        {
            if ((App.Current as App)!.Host.Services.GetService(typeof(T)) is not T service)
            {
                throw new ArgumentException($"{typeof(T)} needs to be registered in ConfigureServices within App.xaml.cs.");
            }
            return service;
        }

        public static WindowEx MainWindow { get; } = new MainWindow();

        public static UIElement? AppTitlebar { get; set; }

        public App()
        {
            InitializeComponent();

            Host = Microsoft.Extensions.Hosting.Host.
            CreateDefaultBuilder().
            UseContentRoot(AppContext.BaseDirectory).
            ConfigureServices((context, services) =>
            {
                // Activation Handlers
                services.AddTransient<ActivationHandler<LaunchActivatedEventArgs>, DefaultActivationHandler>();

                // Services
                services.AddSingleton<ILocalSettingsService, LocalSettingsService>();
                services.AddSingleton<IThemeSelectorService, ThemeSelectorService>();
                services.AddTransient<INavigationViewService, NavigationViewService>();
                services.AddSingleton<IMicaService, MicaService>();
                services.AddSingleton<IActivationService, ActivationService>();
                services.AddSingleton<IPageService, PageService>();
                services.AddSingleton<INavigationService, NavigationService>();
                services.AddSingleton<IFileService, FileService>();

                // Views and ViewModels                                
                services.AddTransient<AdvancedCalculatorViewModel>();
                services.AddTransient<AdvancedCalculatorPage>();
                services.AddTransient<DyNamoMangerViewModel>();
                services.AddTransient<DyNamoMangerPage>();
                services.AddTransient<DyNamoViewModel>();
                services.AddTransient<DyNamoPage>();
                services.AddTransient<OnboardingViewModel>();
                services.AddTransient<OnboardingPage>();
                services.AddTransient<FinanceCalculatorViewModel>();
                services.AddTransient<FinanceCalculatorPage>();
                services.AddTransient<DateCalculatorViewModel>();
                services.AddTransient<DateCalculatorPage>();
                services.AddTransient<CurrencyViewModel>();
                services.AddTransient<CurrencyPage>();
                services.AddTransient<QuadEqnViewModel>();
                services.AddTransient<QuadEqnPage>();
                services.AddTransient<BaseConverterViewModel>();
                services.AddTransient<BaseConverterPage>();
                services.AddTransient<UnitConverterViewModel>();
                services.AddTransient<UnitConverterPage>();
                services.AddTransient<CSurfaceAreaViewModel>();
                services.AddTransient<CSurfaceAreaPage>();
                services.AddTransient<PerimeterViewModel>();
                services.AddTransient<PerimeterPage>();
                services.AddTransient<DiagonalViewModel>();
                services.AddTransient<DiagonalPage>();
                services.AddTransient<SurfaceAreaViewModel>();
                services.AddTransient<SurfaceAreaPage>();
                services.AddTransient<VolumeViewModel>();
                services.AddTransient<VolumePage>();
                services.AddTransient<AreaViewModel>();
                services.AddTransient<AreaPage>();                
                services.AddTransient<SettingsViewModel>();
                services.AddTransient<SettingsPage>();                                
                services.AddTransient<SIViewModel>();                
                services.AddTransient<HFViewModel>();
                services.AddTransient<HFPage>();
                services.AddTransient<CalculatorViewModel>();
                services.AddTransient<CalculatorPage>();
                services.AddTransient<ShellPage>();
                services.AddTransient<ShellViewModel>();
                services.AddTransient<SplashPage>();
                services.AddTransient<SplashViewModel>();

                // Configuration
                services.Configure<LocalSettingsOptions>(context.Configuration.GetSection(nameof(LocalSettingsOptions)));
            }).
            Build();

            UnhandledException += App_UnhandledException;
        }

        protected async override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
        {
            base.OnLaunched(args);

            // 1. Setup Backdrop/Theme Resources
            var micaService = App.GetService<IMicaService>();
            await micaService.LoadMicaSettingAsync();

            var localSettings = Windows.Storage.ApplicationData.Current.LocalSettings;
            bool showSplash = localSettings.Values["ShowSplash"] as bool? ?? true;
            bool isFirstLaunch = localSettings.Values["FirstLaunch"] as bool? ?? true;

            if (!showSplash)
            {
                await FinalizeNavigation(isFirstLaunch, args);
            }
            else
            {
                // Show Splash Flow
                var splashScreen = new SplashPage();
                MainWindow.Content = splashScreen;
                MainWindow.Activate();

                // Wait for splash visibility
                await Task.Delay(1300);

                // Play FadeOut if defined in SplashPage.xaml
                if (splashScreen.Resources.ContainsKey("FadeOutStoryboard"))
                {
                    var fadeOutStoryboard = (Storyboard)splashScreen.Resources["FadeOutStoryboard"];
                    fadeOutStoryboard.Begin();
                    await Task.Delay(400); // Wait for animation
                }

                await FinalizeNavigation(isFirstLaunch, args);
            }
        }

        private async Task FinalizeNavigation(bool isFirstLaunch, Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
        {
            if (isFirstLaunch)
            {
                // First Run: Go to Onboarding
                MainWindow.Content = App.GetService<OnboardingPage>();
            }
            else
            {
                // Returning User: Standard Calculator Launch
                var shellViewModel = App.GetService<ShellViewModel>();
                MainWindow.Content = new ShellPage(shellViewModel);
            }

            MainWindow.Activate();

            // Important: Notify the activation service that the UI is set
            await App.GetService<IActivationService>().ActivateAsync(args);
        }
        private void App_UnhandledException(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e)
        {
            // This prevents the app from closing immediately on a non-fatal error
            // You can log the error here: System.Diagnostics.Debug.WriteLine(e.Message);

            // e.Handled = true; // Uncomment this if you want to try to recover from the crash
        }
    }
}
