<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Lamina</RootNamespace>
    <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win-$(Platform).pubxml</PublishProfile>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
	  <SelfContained>true</SelfContained>
	  <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
	  <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
	  <PackageCertificateKeyFile>Lamina_TemporaryKey.pfx</PackageCertificateKeyFile>
	  <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
	  <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
	  <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
	  <GenerateTestArtifacts>False</GenerateTestArtifacts>
	  <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
	  <WindowsAppSDKBootstrapAutoInitializeOptions_OnNoMatch_ShowUI>false</WindowsAppSDKBootstrapAutoInitializeOptions_OnNoMatch_ShowUI>
	  <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
	  <AppxBundle>Always</AppxBundle>
	  <AppxPackageDir>C:\Users\Master\Downloads\</AppxPackageDir>
	  <PlatformTarget>x64</PlatformTarget>
	  <WindowsPackageType>MSIX</WindowsPackageType>
	  <Version>11.28000.19.0</Version>
	  <AssemblyVersion>11.28000.19.0</AssemblyVersion>
	  <DefaultLanguage>en-US</DefaultLanguage>
	  <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
	  <AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Installer\**" />
    <EmbeddedResource Remove="Installer\**" />
    <None Remove="Installer\**" />
    <Page Remove="Installer\**" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageReference Include="ncalc" Version="7.1.0" />
    <PackageReference Include="WinUIEx" Version="2.9.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="C:\Users\Master\.nuget\packages\microsoft.windowsappsdk\1.7.250606001\buildTransitive\..\include\DeploymentManagerAutoInitializer.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="C:\Users\Master\.nuget\packages\microsoft.windowsappsdk\1.7.250606001\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="C:\Users\Master\.nuget\packages\microsoft.windowsappsdk\1.7.250606001\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="C:\Users\Master\.nuget\packages\microsoft.windowsappsdk\1.7.250606001\buildTransitive\..\include\DeploymentManagerAutoInitializer.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PRIResource Remove="Installer\**" />
  </ItemGroup>
</Project>
