// Generated by Template Studio for WinUI 3 not Me
using Lamina.ViewModels;
using Microsoft.UI.Xaml.Controls;
namespace Lamina.Views;

public sealed partial class MainPage : Page
{
    public MainViewModel ViewModel
    {
        get;
    }

    public MainPage()
    {
        ViewModel = App.GetService<MainViewModel>();
        InitializeComponent();
    }
}
