// Generated by Template Studio for WinUI 3 not Me
using Lamina.ViewModels;
using Microsoft.UI.Xaml.Controls;
namespace Lamina.Views;
public sealed partial class SettingsPage : Page
{
    public SettingsViewModel ViewModel
    {
        get;
    }

    public SettingsPage()
    {
        ViewModel = App.GetService<SettingsViewModel>();
        InitializeComponent();
    }
}
